### ISSUE TITLE
Directory with `5.0` in path always serves 404

### ISSUE THREAD

**Issue by JustinBeckwith** [vercel/serve-handler#139] opened 2021-01-25 00:32 UTC
Lovely library - thank you for building it!  I ran into a rather bizarre problem when trying to debug https://github.com/JustinBeckwith/linkinator/issues/233.  There is a route that looks like `http://localhost:3000/docs/5.0/` which always returns a 404, even with an `index.html` in that local directory.  I have a full simple reproduction here:
https://github.com/JustinBeckwith/serve-bug

The code is simple enough:
```js
const http = require('http');
const serve = require('serve-handler');

http.createServer((req, res) => {
  return serve(req, res, {
    public: '.',
    directoryListing: false,
  });
})
.listen(3000);
```

With a directory structure like this:
```
/
  docs/
    normal/
      index.html
    6/
      index.html
    5.0/
      index.html
```

The routes that go to `docs/normal` and `docs/6` work - only the `5.0` route causes a 404.  Please do let me know if there's anything else I can do to help with a reproduction.  

cc @XhmikosR

**Comment by XhmikosR** [comment] 2021-01-25 13:17
@JustinBeckwith I had a quick look at this and it seems we need

1. to set `renderSingle: true`
2. and change the `=== 1` check to `>= 1` here:
  https://github.com/vercel/serve-handler/blob/c7a40435bc28b420a725e6dc1e9565d5b845dee2/src/index.js#L342

Then linkinator is passing here.

I haven't tested it with unit tests since I'm having trouble setting up the repo on vanilla Windows 10.

@styfle friendly CC in case you can help us here :)

**Comment by styfle** [comment] 2021-02-01 13:56
Thanks for the repro steps!

Indeed, this does look like a duplicate of #120 so I'll close this one.

**Closed by styfle** 2021-02-01 13:56 UTC
Labels: bug
